/*FULLY AI GENERATED CODE, GENERATED BY GEMINI
EVERY FILE THAT HAS THIS AT ITS TOP WAS FULLY AI GENERATED
EVERY OTHER FILE WAS CODED BY ARY-299*/

document.addEventListener("DOMContentLoaded", () => {
    const startBtn = document.getElementById("startBtn");
    const contentArea = document.getElementById("contentArea");
    const topLane = document.getElementById("topLane");
    const hideLaneBtn = document.getElementById("hideLaneBtn");
    const showLaneBtn = document.getElementById("showLaneBtn");
    const userIpSpan = document.getElementById("userIp");
    const serverList = document.getElementById("serverList");

    // Fetch user IP (mock or via free api)
    fetch('https://api.ipify.org?format=json')
        .then(response => response.json())
        .then(data => {
            userIpSpan.textContent = `IP: ${data.ip}`;
        })
        .catch(() => {
            userIpSpan.textContent = `IP: 127.0.0.1`;
        });

    // Start Button Action
    startBtn.addEventListener("click", () => {
        startBtn.style.display = "none";
        contentArea.classList.remove("hidden");
        setTimeout(() => {
            contentArea.classList.add("visible");
            loadMockServers();
        }, 50);
    });

    // Top Lane Toggle Actions
    hideLaneBtn.addEventListener("click", () => {
        topLane.classList.add("hidden");
        showLaneBtn.classList.remove("hidden");
    });

    showLaneBtn.addEventListener("click", () => {
        topLane.classList.remove("hidden");
        showLaneBtn.classList.add("hidden");
    });

    // Mock data mirroring your config.yml structure
    function loadMockServers() {
        const servers = [
            { name: "Keeeks core", ip: "https://Keeeks.de/", ping: "45 ms", statusColor: "green" },
            { name: "Youtube", ip: "https://youtube.com/", ping: "110 ms", statusColor: "yellow" }
        ];

        serverList.innerHTML = "";
        servers.forEach(server => {
            const card = document.createElement("div");
            card.className = "server-card";
            card.innerHTML = `
                <h3>${server.name}</h3>
                <p>URL/IP: ${server.ip}</p>
                <p>Ping: <span style="color: ${server.statusColor};">${server.ping}</span></p>
            `;
            serverList.appendChild(card);
        });
    }
});